# NumPy Student Workbook

Questions only. Write answers in the empty code cells below each question.

Q1. Create a NumPy array containing 10, 20, 30, 40, 50.

In [2]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


Q2. Create numbers from 1 to 20.

In [3]:
a= np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q3. Create even numbers from 2 to 20.

In [4]:
a=np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


Q4. Create a 3×4 matrix of zeros.

In [5]:
a=np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Q5. Create a 4×3 matrix of ones.

In [6]:
a= np.ones([4,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Q6. Generate 10 evenly spaced values between 0 and 1.

In [7]:
a=np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Q7. Create a 2×3 array and find shape, ndim and dtype.

In [8]:
a= np.array([[1,2,3],[4,5,6]])
b=a.shape;
c=a.dtype
d=a.ndim
print(b)
print(c)
print(d)

(2, 3)
int64
2


Q8. Create a 4×5 array and find shape, size and ndim.

In [9]:
a= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
b=a.shape
c=a.ndim
d=a.dtype
print(b)
print(c)
print(d)

(4, 5)
2
int64


Q9. Convert [1,2,3,4,5] to float datatype.

In [10]:
a=np.array([1,2,3,4,5])
b= a.astype(float)
b.dtype

dtype('float64')

Q10. Create numbers 1–12 and reshape into 3×4, 2×6 and 4×3.

In [11]:
a=np.arange(1,13)
b=a.reshape(3,4)
c=a.reshape(2,6)
d=a.reshape(4,3)
print(b)
print(c)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q11. Create np.arange(20) and reshape into 4×5 and 5×4.

In [12]:
a=np.arange(20)
b=a.reshape(4,5)
c=a.reshape(5,4)
print(b)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


Q12. Explain why np.arange(10).reshape(3,4) produces an error.

Because with 10 elements, (3,4) matrix is not poosible. For (3,4) matrix, 12 elements are needed.

Q13. Using a 4×4 array, extract the first element.

In [14]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
b=a[0,0]
print(b)

1


Q14. Extract the value 10 from a 4×4 array created using arange.

In [15]:
a=np.arange(1,17).reshape(4,4)
print(np.where(a==10))

(array([2]), array([1]))


Q15. Extract the last element.

In [16]:
a=np.arange(1,17).reshape(4,4)
b=a[-1,-1]
print(b)

16


Q16. Extract the first row.

In [17]:
a=np.arange(1,17).reshape(4,4)
b=a[0,:]
print(b)

[1 2 3 4]


Q17. Extract the third row.

In [18]:
a=np.arange(1,17).reshape(4,4)
b=a[2,:]
print(b)

[ 9 10 11 12]


Q18. Extract the second column.

In [19]:
a=np.arange(1,17).reshape(4,4)
b=a[:,1]
print(b)

[ 2  6 10 14]


Q19. Extract the last column.

In [20]:
a=np.arange(1,17).reshape(4,4)
b=a[:,-1]
print(b)

[ 4  8 12 16]


Q20. Extract first two rows.

In [21]:
a=np.arange(1,17).reshape(4,4)
b=a[0:2,:]
print(b)

[[1 2 3 4]
 [5 6 7 8]]


Q21. Extract last two rows.

In [22]:
a=np.arange(1,17).reshape(4,4)
b=a[-2:]
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


Q22. Extract first three columns.

In [23]:
a=np.arange(1,17).reshape(4,4)
b=a[:,0:3]
print(b)


[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


Q23. Extract last two columns.

In [24]:
a=np.arange(1,17).reshape(4,4)
b=a[:,-2:]
print(b)

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


Q24. Extract a 2×2 center block.

In [25]:
rows, cols = a.shape

b=a[rows//2 - 1 : rows//2 + 1,
  cols//2 - 1 : cols//2 + 1]
print(b)

[[ 6  7]
 [10 11]]


Q25. Extract bottom-right 3×3 block.

In [26]:
a=np.arange(1,17).reshape(4,4)
b=a[1:4,1:4]
print(b)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


Q26. Extract center element.

In [27]:
a=np.arange(1,10).reshape(3,3)
rows,cols= a.shape
b=a[rows//2,cols//2]
print(b)

5


Q27. Extract center 3×3 block.

In [28]:
a=np.arange(1,26).reshape(5,5)
b=a[1:4,1:4]
print(b)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Q28. Extract top-right corner block.

In [29]:
a=np.arange(1,17).reshape(4,4)
b=a[0:2,2:4]
print(b)

[[3 4]
 [7 8]]


Q29. Extract bottom-left corner block.

In [30]:
a=np.arange(1,17).reshape(4,4)
b=a[2:4,0:2]
print(b)

[[ 9 10]
 [13 14]]


Q30. Extract the main diagonal manually using slicing/indexing.

In [32]:
a=np.arange(1,17).reshape(4,4)
b = []
for i in range(4):
    b.append(int(a[i,i]))
print(b)

[1, 6, 11, 16]


Q31. Extract every alternate row.

In [33]:
a=np.arange(1,17).reshape(4,4)
b=a[::2]
print(b)

[[ 1  2  3  4]
 [ 9 10 11 12]]


Q32. Extract every alternate column.

In [34]:
a=np.arange(1,17).reshape(4,4)
b=a[:,::2]
print(b)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


Q33. Reverse the rows.

In [35]:
a=np.arange(1,17).reshape(4,4)
b=a[::-1]
print(b)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


Q34. Reverse the columns.

In [36]:
a=np.arange(1,17).reshape(4,4)
b=a[:,::-1]
print(b)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


Q35. Reverse the entire matrix.

In [37]:
a=np.arange(1,17).reshape(4,4)
b=a[::-1,::-1]
print(b)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Q36. Extract a 3×3 reversed center block.

In [38]:
a=np.arange(1,26).reshape(5,5)
b=a[::-1,::-1]
c=b[1:4,1:4]
print(c)

[[19 18 17]
 [14 13 12]
 [ 9  8  7]]


Q37. Extract only the corner elements.

In [39]:
a=np.arange(1,17).reshape(4,4)
b=[[int(a[0,0]),int(a[0,-1]),int(a[-1,0]),int(a[-1,-1])]]
print(b)

[[1, 4, 13, 16]]


Q38. Extract only the border elements.

In [40]:
a=np.arange(1,17).reshape(4,4)
b=[]
rows,cols=a.shape
for i in range(rows):
  for j in range(cols):
    if(i==0 or i==rows-1 or j==0 or j==cols-1):
      b.append(int(a[i,j]))
print(b)

[1, 2, 3, 4, 5, 8, 9, 12, 13, 14, 15, 16]


Q39. Increase sales [100,200,300,400] by 10.

In [41]:
a= np.array([100,200,300])
b=a+10
print(b)

[110 210 310]


Q40. Increase salaries by 15%.

In [42]:
salary= np.array([100,200,300])
b=salary+(0.15*salary)
print(b)

[115. 230. 345.]


Q41. Apply 18% GST to prices.

In [43]:
price= np.array([100,200,300])
gst= price*0.18
print(gst)

[18. 36. 54.]


Q42. Subtract 5 from every element.

In [44]:
a= np.array([100,200,300])
b= a-5
print(b)

[ 95 195 295]


Q43. Find total sales.

In [45]:
sales= np.array([100,200,300])
b= sales.sum()
print(b)

600


Q44. Find average sales.

In [46]:
sales= np.array([100,200,300])
b=sales.sum()
c= b/a.size
print(c)

200.0


Q45. Find maximum sales.

In [47]:
sales= np.array([100,200,300])
b=a.max()
print(b)

300


Q46. Find minimum sales.

In [48]:
sales= np.array([100,200,300])
b=a.min()
print(b)

100


Q47. Find standard deviation.

In [49]:
sales= np.array([100,200,300])
stddeviation=np.std(sales)
print(stddeviation)

81.64965809277261


Q48. Find variance.

In [50]:
sales= np.array([100,200,300])
variance=np.var(sales)
print(variance)

6666.666666666667


Q49. Find median.

In [51]:
sales= np.array([100,200,300])
mediansss= np.median(sales)
print(mediansss)

200.0


Q50. Mini Project: Analyze a sales dataset using NumPy.

In [1]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])

data.shape

(1000, 10)

In [2]:
data

array([[ 1001,    52,     2, ...,     2, 18737,     2],
       [ 1002,    93,    15, ...,     4, 12728,     2],
       [ 1003,    15,     8, ...,     1, 16726,     2],
       ...,
       [ 1998,    18,    11, ...,     3, 18505,     4],
       [ 1999,   100,     1, ...,     3, 10564,     1],
       [ 2000,    86,     7, ...,     5, 19793,     3]])

Q1. Dataset Exploration

Find:

Shape
Number of Dimensions
Datatype
Total Number of Elements

In [53]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])

a=data.shape
b=data.ndim
c= data.dtype
d=data.size
print(a)
print(b)
print(c)
print(d)

(1000, 10)
2
int64
10000


Q2. First Look at Data

Display:

First 10 rows

Last 10 rows

In [54]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
a=data[0:10,:]
print(a)

b= data[-10:,:]
print(b)

[[ 1001    52     2  1724     7 30461 12566     2 18737     2]
 [ 1002    93    15  2872    19 13102  2359     4 12728     2]
 [ 1003    15     8  3826    16  9756 10120     1 16726     2]
 [ 1004    72     8  3247     0 21084  1357     5 17481     2]
 [ 1005    61    17  4189    11 47480   564     3 16430     4]
 [ 1006    21    12  4906    25 35181 14162     1 13114     5]
 [ 1007    83    19  2290    18 26292  3394     3 10616     4]
 [ 1008    87    10  1016    14 22404  6874     5 13644     4]
 [ 1009    75     9  4086     8 43861  7531     4 16413     1]
 [ 1010    75     5  2975     6 35040  1330     2 11203     1]]
[[ 1991    17     6  3860     3 22750  2562     5 19344     5]
 [ 1992    13     2  1975     0 19450 13750     5 16985     3]
 [ 1993    84    18  4133    17 17859  9922     2 10947     3]
 [ 1994    25    13  1089     0 24096 13592     2 14760     4]
 [ 1995    68     9  3844    25 26030   387     1 19909     2]
 [ 1996    10    19  2786    25  1762  6053     5 1006

Q3. Using the Sales column:(Sales Column number 5)

Find:

Total Sales

Average Sales

Maximum Sales

Minimum Sales

In [55]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
total_sales = np.sum(data[:,5])
print(total_sales)
avgsales = np.mean(data[:,5])
print(avgsales) 
maxsales = np.max(data[:,5])
print(maxsales)
minsales = np.min(data[:,5])
print(minsales) 

25288432
25288.432
49930
582


Q4. Using the Profit column:(column number 6)

Find:

Total Profit

Average Profit

Maximum Profit

In [56]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
total_profit = np.sum(data[:,6])
print(total_profit) 
avgprofit = np.mean(data[:,6])
print(avgprofit) 
maxprofit = np.max(data[:,6])
print(maxprofit) 

7557939
7557.939
14984


Q5. Indexing Challenge

Display:

Row 100

Row 500

Row 999

In [57]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
row100= data[99,:]
print(row100)
row500= data[499,:]
print(row500) 
row999= data[999,:]
print(row999)

[ 1100    24     5  1562     6 36017  3236     5 15599     4]
[ 1500    67    18  2356    30 36029  4159     1 15580     2]
[ 2000    86     7  2559    22 30268   229     5 19793     3]


Q6. Slicing Challenge

Display:

Rows 100–200

First 5 columns

Last 3 columns

In [58]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
r= data[99:199,:]
print(r) 

firstfivecols=data[:,:5] 
print(firstfivecols)

lastthreecolss= data[:, -3:]
print(lastthreecolss)

[[ 1100    24     5  1562     6 36017  3236     5 15599     4]
 [ 1101    26     5  4776     1 13656  3418     4 11716     3]
 [ 1102    89    19  1684    23 23564  2882     1 10786     1]
 [ 1103    60    14   582    27 26211  9282     1 14368     1]
 [ 1104    41     4  3279     4 30606  7757     5 18096     5]
 [ 1105    29    13  1349     6 17089  5020     4 14272     2]
 [ 1106    15    10  4868     3 24236 13850     4 13767     4]
 [ 1107    45    18   730     4 21475 10445     2 18834     3]
 [ 1108    65     8   761    23 36718  6424     3 15994     1]
 [ 1109    89     8  3603     0  7714  6427     5 17216     3]
 [ 1110    71     7  2952     0 31081  8517     3 18857     2]
 [ 1111     9     8  2566    14 20695   876     3 13426     2]
 [ 1112    88    14  1087    19 45082 11129     5 13783     3]
 [ 1113     1    19  1646    18 27627  5308     4 15427     4]
 [ 1114     8     6   749    28  5641   787     5 17011     2]
 [ 1115    88     1  1068     9 29384   629     3 18052

Q7. Advanced Slicing

Display:

Every alternate row

Every alternate column

Dataset in reverse order

In [59]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
alternaterows= data[::2,:]
print(a)

alternatecol = data[:, ::2]
print(alternatecol)
reversedata = data[::-1]
print(reversedata)

[[ 1001    52     2  1724     7 30461 12566     2 18737     2]
 [ 1002    93    15  2872    19 13102  2359     4 12728     2]
 [ 1003    15     8  3826    16  9756 10120     1 16726     2]
 [ 1004    72     8  3247     0 21084  1357     5 17481     2]
 [ 1005    61    17  4189    11 47480   564     3 16430     4]
 [ 1006    21    12  4906    25 35181 14162     1 13114     5]
 [ 1007    83    19  2290    18 26292  3394     3 10616     4]
 [ 1008    87    10  1016    14 22404  6874     5 13644     4]
 [ 1009    75     9  4086     8 43861  7531     4 16413     1]
 [ 1010    75     5  2975     6 35040  1330     2 11203     1]]
[[ 1001     2     7 12566 18737]
 [ 1002    15    19  2359 12728]
 [ 1003     8    16 10120 16726]
 ...
 [ 1998    11    19  2007 18505]
 [ 1999     1    19  1261 10564]
 [ 2000     7    22   229 19793]]
[[ 2000    86     7 ...     5 19793     3]
 [ 1999   100     1 ...     3 10564     1]
 [ 1998    18    11 ...     3 18505     4]
 ...
 [ 1003    15     8 ...     1 1

Q8. Broadcasting

Management decides to increase all sales by 10%.

Create a new sales array with updated values.

In [60]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
updated_sales = data[:, 5] * 1.10
print(updated_sales)
new_data = data.copy()
new_data[:, 5] = data[:, 5] * 1.10
print(new_data)

[33507.1 14412.2 10731.6 23192.4 52228.  38699.1 28921.2 24644.4 48247.1
 38544.  29739.6 21630.4 14845.6  3708.1 51152.2 25438.6 12123.1 48301.
  1795.2 37363.7 16537.4 26789.4 47847.8 43521.5 50717.7  9143.2  5562.7
  2946.9 48727.8 10521.5  9652.5 53192.7 40092.8 23320.  43960.4 47136.1
 31123.4 32211.3 19247.8 15805.9 49527.5 31517.2 23599.4 35260.5 18869.4
 50078.6 39309.6 52223.6 17096.2 29112.6 53797.7 49295.4 50154.5 16247.
 34548.8 17625.3 52324.8 22540.1 12402.5 14041.5 21954.9 18890.3 30311.6
  7825.4 40172.   8706.5 26020.5 54923.  48822.4 19210.4 42048.6 41298.4
 41848.4 36027.2  4765.2 28352.5 16941.1 42584.3 38112.8 47446.3 25759.8
 51913.4 22044.  13288.  42792.2 42985.8 27958.7 25099.8 11746.9 14026.1
 51038.9 21992.3 23062.6 33776.6 50572.5 22136.4 29770.4 25203.2 31339.
 39618.7 15021.6 25920.4 28832.1 33666.6 18797.9 26659.6 23622.5 40389.8
  8485.4 34189.1 22764.5 49590.2 30389.7  6205.1 32322.4 27923.5  3528.8
 20762.5 17146.8 49612.2 50100.6 11565.4  4150.3 52398

Q9. Business Filtering

Find:

Number of orders where Sales > ₹25,000

Number of orders where Profit > ₹5,000

In [61]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
sales_gt_25000 = np.sum(data[:, 5] > 25000)
print("Orders with Sales > ₹25,000 =", sales_gt_25000)
profit_gt_5000 = np.sum(data[:, 6] > 5000)
print("Orders with Profit > ₹5,000 =", profit_gt_5000)

Orders with Sales > ₹25,000 = 509
Orders with Profit > ₹5,000 = 658


Q10. Management Report

Create a final report showing:

Total Sales

Average Sales

Total Profit

Average Profit

Highest Sale

Highest Profit

Number of High-Value Orders (Sales > ₹25,000)

In [62]:
import numpy as np

np.random.seed(42)

data = np.column_stack([
    np.arange(1001, 2001),                  # Order_ID
    np.random.randint(1, 101, 1000),        # Product_ID
    np.random.randint(1, 20, 1000),         # Quantity
    np.random.randint(100, 5000, 1000),     # Unit_Price
    np.random.randint(0, 31, 1000),         # Discount
    np.random.randint(500, 50000, 1000),    # Sales
    np.random.randint(100, 15000, 1000),    # Profit
    np.random.randint(1, 6, 1000),          # Region_ID
    np.random.randint(10000, 20000, 1000),  # Customer_ID
    np.random.randint(1, 6, 1000)           # Rating
])
total_sales = np.sum(data[:, 5])
average_sales = np.mean(data[:, 5])
total_profit = np.sum(data[:, 6])
average_profit = np.mean(data[:, 6])
highest_sale = np.max(data[:, 5])
highest_profit = np.max(data[:, 6])
high_value_orders = np.sum(data[:, 5] > 25000)
print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Total Profit:", total_profit)
print("Average Profit:", average_profit)
print("Highest Sale:", highest_sale)
print("Highest Profit:", highest_profit)
print("Number of High-Value Orders:", high_value_orders)

Total Sales: 25288432
Average Sales: 25288.432
Total Profit: 7557939
Average Profit: 7557.939
Highest Sale: 49930
Highest Profit: 14984
Number of High-Value Orders: 509
